# Generated by Django 3.1.3 on 2021-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('comment_id', models.IntegerField(db_column='COMMENT_ID', primary_key=True, serialize=False)),
                ('comment_content', models.CharField(blank=True, db_column='COMMENT_CONTENT', max_length=4000, null=True)),
                ('comment_dttm', models.DateTimeField(blank=True, db_column='COMMENT_DTTM', null=True)),
            ],
            options={
                'db_table': 'comment_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('member_id', models.CharField(db_column='MEMBER_ID', max_length=1000, primary_key=True, serialize=False)),
                ('member_nm', models.CharField(blank=True, db_column='MEMBER_NM', max_length=1000, null=True)),
                ('member_tel', models.CharField(blank=True, db_column='MEMBER_TEL', max_length=1000, null=True)),
                ('member_addr', models.CharField(blank=True, db_column='MEMBER_ADDR', max_length=1000, null=True)),
                ('memeber_pass', models.CharField(blank=True, db_column='MEMEBER_PASS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'member_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('news_id', models.IntegerField(db_column='NEWS_ID', primary_key=True, serialize=False)),
                ('news_title', models.CharField(blank=True, db_column='NEWS_TITLE', max_length=1000, null=True)),
                ('news_content', models.TextField(blank=True, db_column='NEWS_CONTENT', null=True)),
                ('news_good', models.IntegerField(blank=True, db_column='NEWS_GOOD', null=True)),
                ('news_notgood', models.IntegerField(blank=True, db_column='NEWS_NOTGOOD', null=True)),
                ('news_dttm', models.DateTimeField(blank=True, db_column='NEWS_DTTM', null=True)),
                ('news_editor', models.CharField(blank=True, db_column='NEWS_EDITOR', max_length=1000, null=True)),
                ('media_outlets', models.CharField(blank=True, db_column='MEDIA_OUTLETS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'news_info',
                'managed': False,
            },
        ),
    ]
